[package]
name = "nwipc-native-peer-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
default-run = "nwipc-native-peer-example"

[dependencies]
nwipc-peer = { version = "=0.0.0", path = "../../crates/peer/nwipc-peer" }

[dev-dependencies]
nwipc = { path = "../../crates/facade/nwipc" }
nwipc-process-testkit = { path = "../../crates/testing/nwipc-process-testkit" }
nwipc-renderer-api.workspace = true
nwipc-types.workspace = true

[lints]
workspace = true
