[package]
name = "nwipc-native-peer-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
default-run = "nwipc-native-peer-example"

[dependencies]
nwipc-peer = { version = "=0.0.0", path = "../../crates/peer/nwipc-peer" }
nwipc-peer-core.workspace = true

[dev-dependencies]
nwipc.workspace = true
nwipc-process-testkit.workspace = true
nwipc-renderer-api.workspace = true
nwipc-types.workspace = true

[lints]
workspace = true
