[package]
name = "nwipc-session-machine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.nwipc]
layer = "runtime"
stability = "experimental"
owner = "nwipc"

[dependencies]
nwipc-error.workspace = true

[lints]
workspace = true
