[package]
name = "nwipc-channel-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.nwipc]
layer = "data-plane"
stability = "experimental"
owner = "nwipc"

[dependencies]
nwipc-atomic.workspace = true
nwipc-error.workspace = true
nwipc-flow-control.workspace = true
nwipc-record.workspace = true
nwipc-ring-reader.workspace = true
nwipc-ring-writer.workspace = true

[dev-dependencies]
nwipc-testkit = { path = "../../testing/nwipc-testkit" }

[lints]
workspace = true
