[package]
name = "nwipc-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[package.metadata.nwipc]
layer = "protocol"
stability = "experimental"
owner = "nwipc"

[dependencies]
nwipc-capabilities.workspace = true
nwipc-error.workspace = true
nwipc-types.workspace = true

[lints]
workspace = true
